//Console.WriteLine("Hello world!");
//string aFriend = "Bill";
//Console.WriteLine(aFriend);
//String aFriend = "Maira";
//Console.WriteLine(aFriend);
//Console.WriteLine("Hello " + aFriend);
//Console.WriteLine("Hello " + aFriend);
string firstFriend = "Maria";
string secondFriend = "Sage";
Console.WriteLine($"My friends are {firstFriend} and {secondFriend}");
Console.WriteLine($"The name {firstFriend} has {firstFriend.Length} letters.");
Console.WriteLine($"The name {secondFriend} has {secondFriend.Length} letters.");
Console.WriteLine($"The name {firstFriend}");
